// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5UuHHTmBDBofvsR7GmtPK_aK22EiVdA',
    appId: '1:135367332994:android:4fd6e95174eff4f5d2d09b',
    messagingSenderId: '135367332994',
    projectId: 'la-ad-21177',
    storageBucket: 'la-ad-21177.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuXyGMaNSXlGfqmkKMw6f0o4WeGKdhQsU',
    appId: '1:135367332994:web:da00eec8a25a4b7ed2d09b',
    messagingSenderId: '135367332994',
    projectId: 'la-ad-21177',
    authDomain: 'la-ad-21177.firebaseapp.com',
    storageBucket: 'la-ad-21177.firebasestorage.app',
    measurementId: 'G-HR7ZYZY3R7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJnc9sLd8-nuxrJQqwXfPj8vgCyi0MNY',
    appId: '1:135367332994:ios:b7334f2872ce45dbd2d09b',
    messagingSenderId: '135367332994',
    projectId: 'la-ad-21177',
    storageBucket: 'la-ad-21177.firebasestorage.app',
    iosBundleId: 'com.example.3laAdElEed',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJnc9sLd8-nuxrJQqwXfPj8vgCyi0MNY',
    appId: '1:135367332994:ios:b7334f2872ce45dbd2d09b',
    messagingSenderId: '135367332994',
    projectId: 'la-ad-21177',
    storageBucket: 'la-ad-21177.firebasestorage.app',
    iosBundleId: 'com.example.3laAdElEed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuXyGMaNSXlGfqmkKMw6f0o4WeGKdhQsU',
    appId: '1:135367332994:web:59c037d239f5e7e7d2d09b',
    messagingSenderId: '135367332994',
    projectId: 'la-ad-21177',
    authDomain: 'la-ad-21177.firebaseapp.com',
    storageBucket: 'la-ad-21177.firebasestorage.app',
    measurementId: 'G-WC35KS582L',
  );

}